import raw from '@/data/abolitionist-churches.json';

/**
 * Publicly-abolitionist churches, for the section on each city page.
 *
 * Source: `data/abolitionist-churches.json`, regenerated by
 * `scripts/sync_abolitionist_churches.py` from an NXR directory export. Do not
 * hand-edit the JSON — fix the directory and re-sync.
 *
 * **A church qualifies by being publicly abolitionist, not by being
 * conservative, confessional or Reformed.** As of the August 2026 sweep the
 * directory holds 106 New Jersey congregations and exactly one of them
 * qualifies. Every one of the other 105 was read; the bar is the bar. Expect
 * `getChurchesByCity` to return nothing for almost every city, and let the
 * page say so plainly.
 *
 * The join key is `municipality`, which is geocoded at sync time — not the
 * mailing city. New Jersey addresses routinely name a place that is not a
 * municipality, and municipality names repeat across counties. The Michigan
 * original carried a hand-maintained alias table for the same problem; this
 * does not need one.
 */

export interface ChurchMinistry {
  name: string;
  url: string;
  description: string | null;
}

export interface AbolitionistChurch {
  id: string;
  name: string;
  denomination: string | null;
  address: string;
  /** Mailing city, as printed on the address. Display only — never join on it. */
  city: string | null;
  /** Geocoded municipality. This is the join key. */
  municipality: string | null;
  county: string | null;
  state: string | null;
  website: string | null;
  phone: string | null;
  email: string | null;
  pastor: string | null;
  /** Internal directory prose. NOT for display — it contains research
   *  bookkeeping written for editors, not for readers. */
  notes: string | null;
  ministries: ChurchMinistry[] | null;
  /** How the stance was established: 'evidenced' = read in the church's own
   *  words; 'mixed' = rests on someone else's listing. */
  stanceBasis?: string | null;
  /** True while the stance is attested but not independently confirmed. */
  verifyStance?: boolean;
  /** The body that lists this church as abolitionist, when the stance comes
   *  from a listing rather than from the church's own output. Shown to the
   *  reader so they can weigh the source themselves. */
  listedBy?: string | null;
  listedByUrl?: string | null;
}

interface RawData {
  note: string;
  syncedAt?: string;
  totalScanned?: number;
  matched?: number;
  churches: AbolitionistChurch[];
}

const DATA = raw as RawData;

export function getAllChurches(): AbolitionistChurch[] {
  return DATA.churches;
}

/**
 * Churches inside a municipality.
 *
 * `municipalityName` must be the municipality (e.g. "Franklin"), not the
 * postal city ("Somerset"). City pages already hold the municipality name,
 * because that is what the generated dataset stores.
 */
export function getChurchesByCity(municipalityName: string): AbolitionistChurch[] {
  const needle = municipalityName.trim().toLowerCase();
  return DATA.churches.filter(
    (c) => (c.municipality || c.city || '').trim().toLowerCase() === needle,
  );
}

/** Sync metadata, so the page can say when the directory was last read. */
export function getChurchesSyncMeta() {
  return {
    syncedAt: DATA.syncedAt || null,
    matched: DATA.matched ?? DATA.churches.length,
    totalScanned: DATA.totalScanned ?? null,
  };
}
