"""Regenerate data/nj-cities.json — the generated half of the city pages.

    python scripts/build_nj_cities.py

Inputs are three intermediates produced by the research pipeline and kept in
the scratchpad, because they are large and derived rather than authored:

  nj_cities_base.json            municipality, county, population, centroid,
                                 districts (polygon intersection against TIGER)
  nj_facility_municipalities.json each facility geocoded to a municipality

Only facts live in the output. The prose for each city is authored by hand in
lib/data/cities.ts, and a city with no entry there does not route.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).parent.parent
SCRATCH = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(".")


def formal_name(name: str, kind: str) -> str:
    """How a New Jerseyan writes the municipality's name in a sentence.

    The Census writes "Trenton city" and "Lakewood township". The first is not
    English and the second is miscapitalised, but the type word is load-bearing
    for townships and boroughs — "Hamilton" alone is ambiguous between Mercer
    and Atlantic counties, and there are four Franklin Townships in the state.
    So: keep the type where it disambiguates, drop it where it just reads
    wrong.
    """
    if kind in ("township", "borough"):
        return f"{name} {kind.capitalize()}"
    return name


def main() -> None:
    cities = json.loads((SCRATCH / "nj_cities_base.json").read_text(encoding="utf-8"))
    facs = json.loads((SCRATCH / "nj_facility_municipalities.json").read_text(encoding="utf-8"))

    by_muni: dict[tuple[str, str], list] = {}
    for f in facs:
        if f.get("municipality"):
            by_muni.setdefault((f["municipality"], f["county"]), []).append(f)

    out = []
    for c in cities:
        hits = by_muni.get((c["name"], c["county"]), [])
        out.append({
            "slug": c["slug"],
            "name": c["name"],
            "kind": c["kind"],
            "formalName": formal_name(c["name"], c["kind"]),
            "county": c["county"],
            "population": c["population"],
            "populationLabel": f"~{c['population']:,} residents",
            "latitude": c["latitude"],
            "longitude": c["longitude"],
            # One list, not Michigan's house/senate split: New Jersey elects a
            # senator and two assembly members from each of the same 40
            # districts. Verified — the upper and lower polygons differ in area
            # by 0.000000%.
            "districts": c["districts"],
            "facilityIds": [f["id"] for f in hits],
        })

    out.sort(key=lambda c: -c["population"])
    doc = {
        "note": ("Generated by scripts/build_nj_cities.py — do not hand-edit. "
                 "Population: US Census sub-county estimates, vintage 2024. "
                 "Districts: polygon intersection of each municipality against the "
                 "2024 TIGER state legislative districts, spot-checked against the "
                 "Census geocoder on 15 city-hall addresses with zero mismatches. "
                 "Facilities are matched by GEOCODED municipality, never by the "
                 "mailing city — 'Somerset' is part of Franklin Township and the "
                 "'Washington' facility is in Warren County, not Washington "
                 "Township, Gloucester."),
        "generated": "2026-08-12",
        "cities": out,
    }
    (REPO / "data" / "nj-cities.json").write_text(
        json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print(f"wrote {len(out)} cities")
    print(f"  spanning >1 district: {sum(1 for c in out if len(c['districts']) > 1)}")
    print(f"  with a facility:      {sum(1 for c in out if c['facilityIds'])}")
    for c in out[:6]:
        print(f"   {c['slug']:14} {c['formalName']:24} {c['county']:11} LD{c['districts']}")


if __name__ == "__main__":
    main()
