/**
 * Typed access to the abolitionist-church list.
 *
 * Source: data/abolitionist-churches.json, which is REGENERATED by
 * scripts/sync-abolitionist-churches.mjs from Dustin's NXR church
 * directory export (Church.json — the abolitionStance='pro_abolition'
 * subset). Don't hand-edit the JSON; re-sync it.
 *
 * Join key with lib/data/cities.ts is city + state — same city name
 * can exist across states (Portland OR vs Portland ME), so both
 * fields are required for a correct match. When the result is empty
 * for a city, the page renders an honest "not aware of any" callout
 * instead of an empty list.
 */

import raw from '@/data/abolitionist-churches.json';

export interface ChurchMinistry {
  name: string;
  url: string;
  description: string | null;
}

export interface AbolitionistChurch {
  id: string;
  name: string;
  denomination: string;
  address: string;
  city: string;
  state: string | null;
  website: string | null;
  phone: string | null;
  email: string | null;
  pastor: string | null;
  notes: string | null;
  /** Associated ministries — mill outreach arms, crisis pregnancy
   * centers, schools, etc. that are formally connected to the church
   * but live on a separate domain. Rendered as secondary links on the
   * church card. */
  ministries: ChurchMinistry[] | null;
}

interface RawData {
  note: string;
  syncedFrom?: string;
  syncedAt?: string;
  totalScanned?: number;
  matched?: number;
  churches: AbolitionistChurch[];
}

const DATA = raw as RawData;

// City aliases for the church-lookup join. Michigan has many city/charter-
// township pairs that share cultural identity and street grid but are
// separate legal entities (Grand Blanc vs Grand Blanc Charter Township,
// etc.); a church physically inside the township is culturally "in" the
// city and should surface on both /cities/[slug] pages. Keys are the
// name we look up with; the values are the OTHER city names that should
// count as equivalent. Bidirectional entries live here (add both directions
// explicitly — the lookup does not walk the graph).
const CITY_ALIASES: Record<string, string[]> = {
  'Grand Blanc': ['Grand Blanc Charter Township'],
  'Grand Blanc Charter Township': ['Grand Blanc'],
};

export function getAllChurches(): AbolitionistChurch[] {
  return DATA.churches;
}

export function getChurchesByCity(cityName: string, state?: string): AbolitionistChurch[] {
  const trimmed = cityName.trim();
  const allowedCities = new Set(
    [trimmed, ...(CITY_ALIASES[trimmed] || [])].map((n) => n.toLowerCase()),
  );
  const stateNeedle = state ? state.trim().toLowerCase() : null;
  return DATA.churches.filter((c) => {
    if (!allowedCities.has(c.city.trim().toLowerCase())) return false;
    if (stateNeedle && (c.state || '').trim().toLowerCase() !== stateNeedle) return false;
    return true;
  });
}

/** Sync metadata for the page footer ("Directory last synced YYYY-MM-DD"). */
export function getChurchesSyncMeta() {
  return {
    syncedAt: DATA.syncedAt || null,
    matched: DATA.matched ?? DATA.churches.length,
    totalScanned: DATA.totalScanned ?? null,
  };
}
